#np.dot(A, B)
#Laske 1-kohdan tehtävät (eli tehtävät 1, 3 ja 5) käyttäen numpyä.

import numpy as np

print("1.a")
A = np.array([[-1, 2], [3, 1]])
B = np.array([[0, 1, 3],  [2, -3, 5]])
C = np.dot(A, B)
print(C)

print("1.b")
A = np.array([[1, 3, 5], [0, -2, 1], [2, -1, 4]])
B = np.array([[1], [-3], [-1]])
C = np.dot(A, B)
print(C)

print("1.c")
A = np.array([[2, 0, 1], [1, -3, 4], [0, 1, 5]])
B = np.array([[3], [-5], [7]])
C = np.dot(A, B)
print(C)

print("1.d")
A = np.array([[1, -4, 2], [3, 0, -2], [2, 1, 0]])
B = np.array([[5, 1, -1],  [-2, 1, 3], [0, 3, 4]])
C = np.dot(A, B)
print(C)

print(80*"-")
print("3.")
print("Rivi- ja sarakemäärien mukaan seuraavat ovat mahdollisia yhdistelmiä: AB, BC ja CB.")
A = np.array([[1, 2, 3], [1, 0, -2]])
B = np.array([[1], [4], [2]])
C = np.array([[1, 0, 2]])
print("AB:")
AB = np.dot(A, B)
print(AB)
print("BC:")
BC = np.dot(B, C)
print(BC)
print("CB")
CB = np.dot(C, B)
print(CB)

print(80*"-")
print("5.")
A = np.array([[1, 0.5], [2, 1]])
B = np.array([[-1, -2], [2, 4]])
print("AB:")
AB = np.dot(A, B)
print(AB)
print("BA")
BA = np.dot(B, A)
print(BA)